# Generated by Django 4.2.11 on 2024-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCB', '0002_remove_measurement_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
