# Generated by Django 4.2.11 on 2024-03-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCB', '0003_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
