# Generated by Django 4.2.11 on 2024-03-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCB', '0005_alter_recipe_count_alter_recipe_rating_userrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
